name: Ping Discord on release

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        id: webhook
        with:
          ack_no_webhook: true
          nodetail: true
          notimestamp: true
          
          username: ReVanced Extended
          content: "<@&1271197877724643461>"
          title: "Patches `${{ github.event.release.tag_name }}` has been released!"
          description: |
            Click [here](${{ github.event.release.html_url }}) to read the changelog and release notes.

      - run: npm install axios
      - uses: actions/github-script@v7
        env:
          WEBHOOK_PAYLOAD: ${{ steps.webhook.outputs.payload }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          script: |
            const axios = require("axios")

            const { WEBHOOK_PAYLOAD, WEBHOOK_URL } = process.env

            const payload = JSON.parse(WEBHOOK_PAYLOAD)

            delete payload.embeds[0].color
            axios.post(WEBHOOK_URL, payload)
